### ISSUE TITLE
リップル削除で選択が外れる

### ISSUE THREAD

**Issue by moss4n** [nazonoSAUNA/tl_Item_cut#1]
お世話になっております。本プラグイン使わせていただいたことで生産性向上し感謝しております。
しかし1点だけ、「リップル削除」するとそれまで選択していたオブジェクトの選択が外れてしまうことが問題と感じています。
可能でしたら、同プラグインの「切り取り」と同様にオブジェクトを選択状態のままにしていただけないでしょうか。
※現状だとオブジェクト選択するためにマウス操作でWクリックが必要となっており連続で分割→リップル削除の操作をする際に障害となっています

実装上困難な箇所でしたら申し訳ありません。ここまで読んでいただきありがとうございます。

**Comment by nazonoSAUNA** [comment]
v5.0にて実装です

**Comment by moss4n** [comment]
あまりにも早い対応に感謝します
